# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picked', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='registry_items')),
            ],
        ),
    ]
